name: Trigger auto deployment for hdp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hdp-AutoDeployTrigger-9b865886-8a09-4dbe-be3e-53c7a9fe6b3d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HDP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HDP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HDP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: testingenv.azurecr.io
          registryUsername: ${{ secrets.HDP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HDP_REGISTRY_PASSWORD }}
          containerAppName: hdp
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: testingenv.azurecr.io/hdp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


